// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HomePage: typeof import('./src/components/HomePage/HomePage.vue')['default']
    HomePageAppBarHeader: typeof import('./src/components/HomePageAppBarHeader.vue')['default']
    HomePageAppBarToolBar: typeof import('./src/components/HomePageAppBarToolBar.vue')['default']
    HomePageHeaderNotificationButton: typeof import('./src/components/HomePageHeaderNotificationButton.vue')['default']
    HomePageSwitchLang: typeof import('./src/components/HomePageSwitchLang.vue')['default']
    IAkarIconsArrowUpDown: typeof import('~icons/akar-icons/arrow-up-down')['default']
    IAntDesignBellFilled: typeof import('~icons/ant-design/bell-filled')['default']
    IAntDesignPlusOutlined: typeof import('~icons/ant-design/plus-outlined')['default']
    IAntDesignSearchOutlined: typeof import('~icons/ant-design/search-outlined')['default']
    IAntDesignUnorderedListOutlined: typeof import('~icons/ant-design/unordered-list-outlined')['default']
    IBxBxsGridAlt: typeof import('~icons/bx/bxs-grid-alt')['default']
    ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    ICarbonAccessibilityAlt: typeof import('~icons/carbon/accessibility-alt')['default']
    ICarbonAccessibilityColor: typeof import('~icons/carbon/accessibility-color')['default']
    ICarbonAccountBox: typeof import('~icons/carbon/account-box')['default']
    IDashiconsArrowDownAlt2: typeof import('~icons/dashicons/arrow-down-alt2')['default']
    IMdiAccountBox: typeof import('~icons/mdi/account-box')['default']
    Logo: typeof import('./src/components/SvgIcon/Logo.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBadge: typeof import('naive-ui')['NBadge']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NP: typeof import('naive-ui')['NP']
    NSelect: typeof import('naive-ui')['NSelect']
  }
}

export { }
