// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HomePageAppBarHeader: typeof import('./src/components/HomePageAppBarHeader.vue')['default']
    HomePageAppBarToolBar: typeof import('./src/components/HomePageAppBarToolBar.vue')['default']
    HomePageHeaderNotificationButton: typeof import('./src/components/HomePageHeaderNotificationButton.vue')['default']
    HomePageSwitchLang: typeof import('./src/components/HomePageSwitchLang.vue')['default']
    HomePageTabListItem: typeof import('./src/components/HomePageTabListItem.vue')['default']
    IAkarIconsArrowUpDown: typeof import('~icons/akar-icons/arrow-up-down')['default']
    IAkarIconsVideo: typeof import('~icons/akar-icons/video')['default']
    IAntDesignAudioFilled: typeof import('~icons/ant-design/audio-filled')['default']
    IAntDesignBellFilled: typeof import('~icons/ant-design/bell-filled')['default']
    IAntDesignBookOutlined: typeof import('~icons/ant-design/book-outlined')['default']
    IAntDesignPlusOutlined: typeof import('~icons/ant-design/plus-outlined')['default']
    IAntDesignSearchOutlined: typeof import('~icons/ant-design/search-outlined')['default']
    IAntDesignUnorderedListOutlined: typeof import('~icons/ant-design/unordered-list-outlined')['default']
    IBxBxsGridAlt: typeof import('~icons/bx/bxs-grid-alt')['default']
    IClarityImageGalleryLine: typeof import('~icons/clarity/image-gallery-line')['default']
    IFaSolidMask: typeof import('~icons/fa-solid/mask')['default']
    IIcomoonFreeNewspaper: typeof import('~icons/icomoon-free/newspaper')['default']
    IUilJackhammer: typeof import('~icons/uil/jackhammer')['default']
    Logo: typeof import('./src/components/SvgIcon/Logo.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBadge: typeof import('naive-ui')['NBadge']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NP: typeof import('naive-ui')['NP']
    NSelect: typeof import('naive-ui')['NSelect']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
  }
}

export { }
